languge: java
jdk:
  - openjdk8

branches:
  only:
    - master


# travis ci 서버와 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# ci 실행 완료시 메일로 알람

notifications:
  email:
    recipients:
      - cheon2229@naver.com

